version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL:-https://estrip.fun}
        - VITE_VAPID_PUBLIC_KEY=${VITE_VAPID_PUBLIC_KEY:-BE_cpojus2_nYd4aTJdzHTL-b9f-Csp5RTBez_2cmyB96lkrJN3AW-GBuDNOr7L9sTug9kmNmZud0Y6e90TbUj0}
    image: longtran26/wc2026:latest
    ports:   # <--- Chữ p này phải thẳng hàng với chữ i của image
      - "5005:5005"
    environment: # <--- Chữ e này cũng phải thẳng hàng
      - DATABASE_URL=postgres://user:pass@db:5432/worldcup2026
      - CORS_ORIGIN=*
      - JWT_SECRET=worldcup2026_secret_key_prod_by_antigravity
      - VAPID_PUBLIC_KEY=BE_cpojus2_nYd4aTJdzHTL-b9f-Csp5RTBez_2cmyB96lkrJN3AW-GBuDNOr7L9sTug9kmNmZud0Y6e90TbUj0
      - VAPID_PRIVATE_KEY=ixGqkAeBMHOD7KKUwYmONKxpwjQC9j6DVDhrvNFYTWY
      - TZ=Asia/Ho_Chi_Minh
    depends_on: # <--- Chữ d này cũng thẳng hàng
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=worldcup2026
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
