version: '3.8'

services:
  app:
    image: longtran26/wc2026:latest
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/worldcup2026
      - CORS_ORIGIN=*
      - JWT_SECRET=worldcup2026_secret_key_prod_by_antigravity
      - VAPID_PUBLIC_KEY=BE_cpojus2_nYd4aTJdzHTL-b9f-Csp5RTBez_2cmyB96lkrJN3AW-GBuDNOr7L9sTug9kmNmZud0Y6e90TbUj0
      - VAPID_PRIVATE_KEY=ixGqkAeBMHOD7KKUwYmONKxpwjQC9j6DVDhrvNFYTWY
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=worldcup2026
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
